version: '3.7'
networks:
  avalanche:
    name: avalanche

services:
  node:
    image: "sonntuet1997/avalanche-simplified:latest"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MODULE=worker
    environment:
      APP_PROFILES: prod
      APP_PATH: /
    networks:
      - avalanche
  client_node:
    image: "sonntuet1997/avalanche-client_node:latest"
    build:
      dockerfile: Dockerfile
      target: base_with_mod
    volumes:
      - .:/go/src/avalanche
    working_dir: /go/src/avalanche
    command: sleep 1000000
    networks:
      - avalanche