app:
  port: 8000
  logging.development: false
  cron:
    jobs:
      selfIntroductionJob:
        expression: "@every 20s"
      fetchTransactionJob:
        expression: "@every 500ms"
  p2p:
    broadcastPort: 5555
    minConnectedNodes: 14 # (n) wait until reach a minimum number of participants to start
  consensus:
    k: 10 #(sample size): between 1 and n
    alpha: 7 #(quorum size): between 1 and k
    beta: 10 #(decision threshold): >= 1
    timeout: "20s" # max duration to collect other nodes preferences
  random:
    range: 2