app:
  port: 8000
  logging.development: true
  cron:
    jobs:
      SelfIntroductionJob:
        expression: "@every 2s"
        disable: true
  p2p:
    listenToBroadcast: false
    broadcastPort: 5555
  consensus:
    n: 200 # number of participants
    k: 10 # (sample size): between 1 and n
    alpha: 6 # (quorum size): between 1 and k
    beta: 4 # (decision threshold): >= 1
