// Code generated by cli. DO NOT EDIT.

package bootstrap

import (
	"gitlab.com/golibs-starter/golib"
	"go.uber.org/fx"
)

func GeneratedConfig() fx.Option {
	return fx.Options(
		golib.AppOpt(),
		golib.PropertiesOpt(),
		golib.LoggingOpt(),
		golib.EventOpt(),
		golib.BuildInfoOpt(Version, CommitHash, BuildTime),
		golib.ActuatorEndpointOpt(),
		// Graceful shutdown.
		// OnStop hooks will run in reverse order.
		// golib.OnStopEventOpt() MUST be first
		golib.OnStopEventOpt(),
	)
}
